version: "3.7"

services:
  sample:
    build: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  default:
    external:
      name: api-ecf_default
